### ISSUE TITLE
유저전체정보 API가 필요합니다.

### ISSUE THREAD

**Issue by jjeonmin** [nhnacademy-be6-code-quest/service-client#3]
clientId, client_name 이 page 형태로 사용자에게 쿠폰 지급 용도로 필요합니다.

**Comment by bakhuiwon326** [comment]
'주문페이지'에서 주문자 정보 가져올 때 필요합니다.

- 사용자이름
- 주소 정보 리스트(주소별칭, 우편번호, 주소, 상세주소)
- 전화번호리스트

**Comment by gihwanJang** [comment]
GET "/api/client"

<param>
int page
int size

<return>
ResponseEntity<Page<ClientCouponPaymentResponseDto>>
